# Generated by Django 5.2.1 on 2025-06-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12002_percent_sign_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loadstaging",
            name="nodegroup",
            field=models.ForeignKey(
                blank=True,
                db_column="nodegroupid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.nodegroup",
            ),
        ),
    ]
