# Generated by Django 5.2 on 2025-05-01 09:15

import arches.app.models.query_expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12008_alter_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="tilemodel",
            name="localized_string_values",
            field=models.GeneratedField(
                db_persist=True,
                expression=arches.app.models.query_expressions.JSONBPathQueryArray(
                    "data", models.Value("$.*.*.value")
                ),
                output_field=models.JSONField(),
            ),
        ),
    ]
