# Generated by Django 6.0.dev20250522121658 on 2025-05-22 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12002_percent_sign_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="graph",
            field=models.ForeignKey(
                blank=True,
                db_column="graphid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.graphmodel",
            ),
        ),
    ]
