# Generated by Django 5.2.2 on 2025-06-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '12000_update_serialized_graph_functions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='editlog',
            index=models.Index(fields=['timestamp'], name='edit_log_timesta_75422b_idx'),
        ),
    ]
